### ISSUE TITLE
Index OOB when attempting to get link to VOD

### ISSUE THREAD

**Issue by AdamSaketume26** [PaaaulZ/TwitchRecover#9] opened 2022-04-12 21:15 UTC
```
Welcome to Twitch Recover!
The number one Twitch recovery tool created by Daylam Tayari (https://github.com/daylamtayari)
This is a fork by PaaaulZ (https://github.com/PaaaulZ) made to fix some bugs since the main developer is now inactive


Menu:

VODs:
1. Get the link to a VOD (including sub-only).
2. Download a VOD (including sub-only).
3. Recover a VOD - 60 days maximum (can be less in rare cases).

Highlights:
4. Retrieve the link to a highlight.
5. Download a highlight.
6. Recover a highlight.

Videos:
7. Check if a VOD/highlight has muted segments.
8. 'Unmute' a VOD/highlight (be able to view the muted segments of the M3U8).
9. Download an M3U8 file.
10. Convert a TS file to MP4.

Clips:
11. Retrieve permanent link of a clip - never deleted.
12. Download a clip.
13. Recover ALL clips from a stream - NO time limit.
Please enter the number of the option you want to select (number between 1-13 inclusive): 1

VOD URL retrieval:
Please enter the link: https://www.twitch.tv/videos/1453629980
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:659)
        at java.util.ArrayList.get(ArrayList.java:435)
        at TwitchRecover.Core.API.VideoAPI.getSubVODFeeds(VideoAPI.java:80)
        at TwitchRecover.Core.VOD.getVODFeeds(VOD.java:113)
        at TwitchRecover.CLI.Handlers.VODHandler.retrieve(VODHandler.java:38)
        at TwitchRecover.CLI.Handlers.VODHandler.<init>(VODHandler.java:18)
        at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:24)
        at TwitchRecover.CLI.CLI.main(CLI.java:13)
        ```

App keeps crashing with Index OOB. The main repo has no issue getting the link to the VOD.

**Comment by PaaaulZ** [comment] 2022-04-23 15:09
Duplicate of #6 and fixed in release v.1.0.2-beta

**Closed by PaaaulZ** 2022-04-23 15:09 UTC
Labels: duplicate
